language: node_js
node_js:
- 0.1
env:
  global:
    # travis encrypt COVERALLS_REPO_TOKEN=foo
  - secure: "Tv3PXlLr33ETZpDaXw1k1ofh+20fIvvPVA3fLR5FtnQUdlLuUQsE+FIqyt9QgN++/zj1gSiNif/aHASo3qQJ6aZiX0cOcLJZ9CHG7b8eBHy6luEGplBsJaFLE9awRhx/d1pe9kCRY3NyY8UkrbGQp+RN5KHBhPrJrzusRTxjopg="
script: make travis
